baseURL = "https://hackerinnen.space"
languageCode = "en-us"
title = "hackerinnen.space"

DefaultContentLanguage = "en"

paginate = 9

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.de]
    languageName = "Deutsch"
    description = "Hackerinnen aller Orte, zeigt euch! Ein Mutmach-Projekt."
    weight = 2

[params]
  description = "Hackerinnen of all places, show yourselves! - A project to provide encouragement and enhance visibility."
  twitter_handle = "@hackerinnen"

[taxonomies]
  tag = "tags"
  cities = "cities"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
