[context.production.environment]
  HUGO_VERSION = "0.79.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.79.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
